# Generated by Django 6.0.2 on 2026-02-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
