# Generated by Django 6.0 on 2026-03-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='urgency',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
