# Generated by Django 6.0 on 2026-03-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resourcerequest_description_resourcerequest_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='feedback_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='feedback_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
