# Generated by Django 6.0 on 2026-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_worker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
