# Generated by Django 6.0 on 2026-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_complaint_resolution_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='value',
            field=models.JSONField(default=False),
        ),
    ]
