# Generated by Django 6.0 on 2026-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_globalsetting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
