# Generated by Django 6.0 on 2026-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_maintenanceschedule_notes_maintenanceschedule_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly'), ('quarterly', 'Every 3 Months')], default='weekly', max_length=20)),
                ('recurrence_value', models.CharField(blank=True, default='', max_length=100)),
                ('time', models.TimeField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
