# Generated by Django 6.0 on 2026-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_recurring_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('missed', 'Missed Task'), ('reminder', 'Reminder'), ('info', 'Info')], default='missed', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('sent_by', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
