# Generated by Django 6.0 on 2026-03-12 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_schedule_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recurringtask'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
